AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pinyin API
  
Globals:
  Function:
    Timeout: 30

Resources:
  PinyinApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          JWTAuthorizer:
            IdentitySource: '$request.header.Authorization'
            JwtConfiguration: 
              audience: 
              - ExlCloudApp:!~test
              issuer: https://apps01.ext.exlibrisgroup.com/auth
            Name: JwtAuthorizer 
        # Uncomment this line to use the JWT authorizer for all routes
        # DefaultAuthorizer: JWTAuthorizer  
      CorsConfiguration:
        AllowOrigins:
          - "https://apps01.ext.exlibrisgroup.com"
          - "http://localhost:4200"
        AllowHeaders: [authorization, content-type]
        AllowMethods: [GET, OPTIONS]
        AllowCredentials: True
        MaxAge: 600
  PinyinFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Layers:
        - !Ref PinyinDependencies
      Runtime: nodejs12.x
      MemorySize: 1028
      FunctionName: PinyinTransliteration
      Events:
        PinyinApi:
          Type: HttpApi
          Properties:
            ApiId: !Ref PinyinApi
            Path: /pinyin/{text}
            Method: get
  PinyinDependencies:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AWS::StackName}-Dependencies"
      Description: Dependencies for Pinyin API app
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

Outputs:
  PinyinApi:
    Description: "Endpoint URL"
    Value: !Sub "https://${PinyinApi}.execute-api.${AWS::Region}.amazonaws.com/pinyin/"
